[env:drone-remote]
platform = espressif32
board = m5stick-c-plus2
framework = arduino
lib_deps =
    m5stack/M5StickCPlus2 @ ^2.1.0
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^7.0.0
monitor_speed = 115200
upload_speed = 1500000
